FROM node:20-alpine AS build
WORKDIR /app
COPY admin-dashboard/package*.json ./
RUN npm ci
COPY admin-dashboard ./
RUN npm run build

FROM caddy:2-alpine
COPY --from=build /app/dist /usr/share/caddy
COPY admin-dashboard/Caddyfile /etc/caddy/Caddyfile
